on:
  push:
    branches:
      - master

name: Build LOCALSTRIPE Docker Image and Deploy to ECS Service

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
        role-duration-seconds: 1200
        role-session-name: GitActionDeploymentSession

    - name: Build the Image
      id: build-image
      continue-on-error: true
      uses: aws-actions/aws-codebuild-run-build@v1.0.3
      with:
        project-name: localstripe-gh-action

    - name: Fill in new Image ID to TaskDef 
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: taskdef.json
        container-name: localstripe
        image: "910496926562.dkr.ecr.us-east-1.amazonaws.com/localstripe:master"

    - name: Deploying the Docker Image to AWS ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: localstripe
        cluster: devops
        wait-for-service-stability: true
