on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: GitHub Branch Name
        required: true

name: Manual build LOCALSTRIPE Docker Image and Deploy to ECS Service

jobs:
  deploy:
    name: Manual Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
        role-duration-seconds: 1200
        role-session-name: GitActionDeploymentSession

    - name: Build the Image
      id: build-image
      uses: aws-actions/aws-codebuild-run-build@v1.0.3
      with:
        project-name: localstripe-gh-action
        env-vars-for-codebuild: BRANCH_NAME
      env:
        BRANCH_NAME: ${{ github.event.inputs.branch_name }}

    - name: Fill in new Image ID to TaskDef 
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: taskdef.json
        container-name: localstripe
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploying the Docker Image to AWS ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: localstripe
        cluster: devops
        wait-for-service-stability: true
